### ISSUE TITLE
Переводчики/тестировщики

### ISSUE THREAD

**Issue by e107club** [e107club/localization_e107_2.1.6_Russian_ru_RU-utf8#1]
Есть ли в нашем сообществе люди, желающие помочь с переводом версии 2.1.x на русский язык, а также тестировщики уже имеющейся на данный момент локализации для отлова возможных ошибок? Присоединяйтесь.

**Comment by Jimmi08** [comment]
Большое вам спасибо за всю вашу работу.  
Просто примечание: эту версию невозможно инсталлировать из администратора, будете в будущем актуализоваť офисыалную верзиу? 
Если вы не хотите тратить свое время, я могу сделать это. 
Проще просто щелкнуть и установить чем затем использовать ftp.

**Comment by net1313** [comment]
Когда закончим, то предложим нашу версию на GitHub официальному сайту e107. И если они будут согласны, то конечно перевод можно будет установить из панели Администратора.

**Comment by Jimmi08** [comment]
@net1313  Просто запрос доступ к русскому репозитарию. В настоящее время он разделен.   (and be aware about my level of Russian).  Я так радa, что ты переводишь его. Cпасибо опять.

**Comment by e107club** [comment]
Скоро, к нам присоединиться команд, который на основе нашей локализации, будет делать украинскую. Зовут его - panikajo.
Эрик, не могу со смартфона послать ему инвайт, если не трудно, сделай.

**Comment by net1313** [comment]
Инвайт могу отправить на свой репозиторий, который я форкнул  с этого.
Сделал отдельно каталоги. Для темы, для плагинов и отдельный (Russian) для локализации ядра.

**Comment by e107club** [comment]
@net1313, Сейчас сам отправлю инвайт, с компа, со смартфона не получается.

**Comment by net1313** [comment]
New branch of language pack is available here https://github.com/e107club/localization_e107_2.1.7_Russian_ru_RU-utf8
These one is old and will be not supported.

Данная версия устарела и больше не будет поддерживаться (в связи с выходом 2.1.7)
Новая ветка тут

https://github.com/e107club/localization_e107_2.1.7_Russian_ru_RU-utf8
