### ISSUE TITLE
структура каталогов

### ISSUE THREAD

**Issue by Jimmi08** [e107club/localization_e107_2.1.6_Russian_ru_RU-utf8#2]
когда я скачаю zip здесь, он имеет плохую структуру. Это намерение? (не имена каталогов, но  расположение каталогов)

Плагин taqwords удален, больше не используется
Плагин social содержит английские файлы

**Comment by net1313** [comment]
Плагин Social переведен, но пока не залит на GitHub.
Пока не скачивайте каталог e107_plugin. Скоро сделаем отдельную ветку (branch) для плагинов.

**Comment by Jimmi08** [comment]
No, I meant that there are both languages. I try this traslation on my site, it looks good.
 
![image](https://user-images.githubusercontent.com/5429548/33606414-af2a83cc-d9bd-11e7-8e27-4f40d327bb44.png)

**Comment by Jimmi08** [comment]
Only serious problem I found that with Russian lang Facebook comment system doesn't work - it works with Italien, so it's not problem with multilan site. I am trying to find the reason.

**Comment by net1313** [comment]
Fixed

**Comment by net1313** [comment]
New branch of language pack is available here https://github.com/e107club/localization_e107_2.1.7_Russian_ru_RU-utf8
These one is old and will be not supported.

Данная версия устарела и больше не будет поддерживаться (в связи с выходом 2.1.7)
Новая ветка тут

https://github.com/e107club/localization_e107_2.1.7_Russian_ru_RU-utf8
