### ISSUE TITLE
Проблема с комментариями через facebook

### ISSUE THREAD

**Issue by Jimmi08** [e107club/localization_e107_2.1.6_Russian_ru_RU-utf8#3]
Причина: 
```
Correct paths:
js.src = '//connect.facebook.net/en_GB/sdk.js';
js.src = '//connect.facebook.net/it_IT/sdk.js';
Wrong path:
js.src = '//connect.facebook.net/'ru_'RU/sdk.js';
```
Fix in Russian.php:
```
define("CORE_LC", "ru");
define("CORE_LC2", "Ru");
```
перед тем: 
```
define("CORE_LC", "'ru");
define("CORE_LC2", "'Ru");
```

![image](https://user-images.githubusercontent.com/5429548/33609383-265157d2-d9c8-11e7-874f-15556cd09d5e.png)

Теперь это выглядит правильно:
 
 
![image](https://user-images.githubusercontent.com/5429548/33609839-f0054808-d9c9-11e7-9ab7-163e8d0986c9.png)

**Comment by net1313** [comment]
Thanks! It's fixed now.

**Comment by Jimmi08** [comment]
You are welcome. You can see frontend on my site. I can't get theme strings translated but it looks like core issue.
